services:
  kiwix-serve:
    container_name: kiwix
    restart: unless-stopped
    profiles: ['kiwix']
    image: ghcr.io/kiwix/kiwix-serve:latest
    volumes:
      - /mnt/routersmb/backups/kiwixdata:/data
    ports:
      - "${WEBUI_PORT_KIWIX}:8080"
    command:
      - '*.zim'
